# Generated by Django 5.2.9 on 2025-12-06 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPreenchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Preenchimento',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='MotivoStatusManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Status Manual',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, default='', max_length=10)),
                ('descricao', models.CharField(max_length=150)),
                ('cod_origem_tiss', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('EXTERNO', 'Externo'), ('PAPABRASIL', 'Papabrasil'), ('PARCEIRO', 'Parceiro'), ('OUTRO', 'Outro')], default='EXTERNO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'ordering': ('codigo', 'descricao'),
            },
        ),
        migrations.CreateModel(
            name='StatusRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('permite_edicao', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status da Requisição',
                'verbose_name_plural': 'Status das Requisições',
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(default='', max_length=10)),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ('codigo', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='PortadorRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PORTADOR', 'Portador'), ('REPRESENTANTE', 'Representante')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portadores', to='operacao.origem')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portadores', to='operacao.unidade')),
            ],
            options={
                'verbose_name': 'Portador / Representante',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_req', models.CharField(max_length=30, unique=True, verbose_name='Código da requisição')),
                ('cod_barras_req', models.CharField(max_length=64, unique=True, verbose_name='Código de barras')),
                ('lote_req', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('data_envio_representante', models.DateField(blank=True, null=True)),
                ('data_cadastro_representante', models.DateField(blank=True, null=True)),
                ('data_recebimento_nto', models.DateField(blank=True, null=True)),
                ('data_um', models.DateField(blank=True, null=True)),
                ('nome_paciente', models.CharField(blank=True, max_length=200)),
                ('cpf_paciente', models.CharField(blank=True, max_length=14)),
                ('data_nasc_paciente', models.DateField(blank=True, null=True)),
                ('sexo_paciente', models.CharField(blank=True, max_length=10)),
                ('telefone_paciente', models.CharField(blank=True, max_length=20)),
                ('email_paciente', models.EmailField(blank=True, max_length=254)),
                ('crm', models.CharField(blank=True, max_length=20, verbose_name='CRM')),
                ('uf_crm', models.CharField(blank=True, max_length=2, verbose_name='UF CRM')),
                ('nome_medico', models.CharField(blank=True, max_length=200)),
                ('end_medico', models.CharField(blank=True, max_length=255, verbose_name='Endereço médico')),
                ('dest_medico', models.CharField(blank=True, max_length=255, verbose_name='Destino médico')),
                ('flag_req_sem_cpf', models.BooleanField(default=False)),
                ('flag_ass_paciente', models.BooleanField(default=False)),
                ('flag_ass_medico', models.BooleanField(default=False)),
                ('flag_carimbo_medico', models.BooleanField(default=False)),
                ('flag_ocr', models.BooleanField(default=False)),
                ('flag_erro_preenchimento', models.BooleanField(default=False)),
                ('korus_bloqueado', models.BooleanField(default=False)),
                ('liberacao_status', models.CharField(blank=True, max_length=30)),
                ('liberacao_descricao', models.TextField(blank=True)),
                ('usuario_edicao', models.CharField(blank=True, max_length=60)),
                ('usuario_cod_barras', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('motivo_preenchimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacao.motivopreenchimento')),
                ('motivo_status_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacao.motivostatusmanual')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='operacao.origem')),
                ('portador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_portador', to='operacao.portadorrepresentante')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_representante', to='operacao.portadorrepresentante')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='operacao.statusrequisicao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='operacao.unidade')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_barras_amostra', models.CharField(max_length=64)),
                ('data_hora_bipagem', models.DateTimeField()),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='operacao.requisicao')),
            ],
            options={
                'verbose_name': 'Amostra',
                'ordering': ('requisicao', 'ordem'),
                'unique_together': {('requisicao', 'cod_barras_amostra')},
            },
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['cod_barras_req'], name='operacao_re_cod_bar_f19d26_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['status'], name='operacao_re_status__ca1822_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['unidade'], name='operacao_re_unidade_40146b_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicao',
            index=models.Index(fields=['data_recebimento_nto'], name='operacao_re_data_re_6ae380_idx'),
        ),
    ]
