# Generated by Django 5.2.9 on 2025-12-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_barras_req', models.CharField(max_length=64, unique=True, verbose_name='Código de barras da requisição')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Payload bruto')),
            ],
            options={
                'verbose_name': 'Dados da requisição',
                'verbose_name_plural': 'Dados das requisições',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['cod_barras_req'], name='operacao_da_cod_bar_825bab_idx')],
            },
        ),
    ]
