# Generated by Django 5.2.9 on 2025-12-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amostra',
            options={'ordering': ('requisicao', 'ordem'), 'verbose_name': 'Amostra', 'verbose_name_plural': 'Amostras'},
        ),
        migrations.AlterUniqueTogether(
            name='amostra',
            unique_together={('requisicao', 'ordem')},
        ),
    ]
