# Generated by Django 5.2.9 on 2025-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_corrigir_unique_amostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrequisicao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
