# Generated by Django 5.2.9 on 2025-12-07 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_dadosrequisicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoStatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_req', models.CharField(db_index=True, help_text='Código da requisição (desnormalizado para performance)', max_length=30, verbose_name='Código da requisição')),
                ('data_registro', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora do registro')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre a mudança de status', verbose_name='Observação')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='operacao.requisicao', verbose_name='Requisição')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='operacao.statusrequisicao', verbose_name='Status')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_status_requisicoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ('-data_registro',),
                'indexes': [models.Index(fields=['requisicao', '-data_registro'], name='operacao_re_requisi_e9d37f_idx'), models.Index(fields=['cod_req', '-data_registro'], name='operacao_re_cod_req_7da7c2_idx'), models.Index(fields=['status', '-data_registro'], name='operacao_re_status__6589d6_idx')],
            },
        ),
    ]
