# Generated by Django 5.2.9 on 2025-12-07 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0003_add_requisicao_status_historico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='recebido_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que recebeu/criou a requisição no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
    ]
