# Generated by Django 5.2.9 on 2025-12-08 01:01

import django.db.models.deletion
from django.db import migrations, models


def migrar_dados_portador(apps, schema_editor):
    """
    Copia dados do campo 'portador' para 'portador_representante'.
    Prioriza 'portador' pois é o campo que está sendo usado.
    Se 'portador' for NULL, tenta copiar de 'representante'.
    """
    DadosRequisicao = apps.get_model('operacao', 'DadosRequisicao')
    
    for req in DadosRequisicao.objects.all():
        if req.portador_id:
            req.portador_representante_id = req.portador_id
        elif req.representante_id:
            req.portador_representante_id = req.representante_id
        req.save(update_fields=['portador_representante'])


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0003_adicionar_campo_ativo'),
    ]

    operations = [
        # 1. Adicionar novo campo
        migrations.AddField(
            model_name='dadosrequisicao',
            name='portador_representante',
            field=models.ForeignKey(
                blank=True,
                help_text='Pessoa que trouxe/enviou a requisição',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requisicoes',
                to='operacao.portadorrepresentante',
                verbose_name='Portador/Representante'
            ),
        ),
        
        # 2. Migrar dados
        migrations.RunPython(migrar_dados_portador, migrations.RunPython.noop),
        
        # 3. Remover campos antigos
        migrations.RemoveField(
            model_name='dadosrequisicao',
            name='portador',
        ),
        migrations.RemoveField(
            model_name='dadosrequisicao',
            name='representante',
        ),
        
        # 4. Atualizar related_name de origem
        migrations.AlterField(
            model_name='dadosrequisicao',
            name='origem',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requisicoes_origem',
                to='operacao.origem'
            ),
        ),
    ]
