# Generated by Django 5.2.9 on 2025-12-08 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0005_adicionar_model_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(help_text='Descrição do tipo de arquivo', max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Arquivo',
                'verbose_name_plural': 'Tipos de Arquivo',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='RequisicaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_req', models.CharField(db_index=True, help_text='Código da requisição (desnormalizado para performance)', max_length=30, verbose_name='Código da requisição')),
                ('nome_arquivo', models.CharField(help_text='Nome original do arquivo enviado', max_length=255, verbose_name='Nome do arquivo')),
                ('url_arquivo', models.CharField(help_text='URL ou caminho do arquivo armazenado', max_length=500, verbose_name='URL do arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de upload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(help_text='Requisição à qual o arquivo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='operacao.dadosrequisicao', verbose_name='Requisição')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tipo_arquivo', models.ForeignKey(help_text='Tipo/categoria do arquivo', on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='operacao.tipoarquivo', verbose_name='Tipo de Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo da Requisição',
                'verbose_name_plural': 'Arquivos das Requisições',
                'ordering': ('-data_upload',),
                'indexes': [models.Index(fields=['requisicao', '-data_upload'], name='operacao_re_requisi_625ff3_idx'), models.Index(fields=['cod_req', '-data_upload'], name='operacao_re_cod_req_953470_idx'), models.Index(fields=['tipo_arquivo', '-data_upload'], name='operacao_re_tipo_ar_31488e_idx')],
            },
        ),
    ]
