# Generated by Django 5.2.9 on 2025-12-16 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0014_popular_tipos_pendencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Criar tabela TipoAmostra
        migrations.CreateModel(
            name='TipoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(help_text='Descrição do tipo de amostra', max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Indica se o tipo de amostra está disponível para uso', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Amostra',
                'verbose_name_plural': 'Tipos de Amostra',
                'db_table': 'tipo_amostra',
                'ordering': ('descricao',),
            },
        ),
        # 2. Remover campo antigo tipos_amostra_id
        migrations.RemoveField(
            model_name='requisicaoamostra',
            name='tipos_amostra_id',
        ),
        # 3. Adicionar flags da Etapa 3 em DadosRequisicao
        migrations.AddField(
            model_name='dadosrequisicao',
            name='flag_problema_cpf',
            field=models.BooleanField(default=False, help_text='Indica problema identificado no CPF do paciente', verbose_name='Problema com CPF'),
        ),
        migrations.AddField(
            model_name='dadosrequisicao',
            name='flag_problema_medico',
            field=models.BooleanField(default=False, help_text='Indica problema identificado nos dados do médico', verbose_name='Problema com dados do médico'),
        ),
        # 4. Adicionar ForeignKey tipo_amostra em RequisicaoAmostra
        migrations.AddField(
            model_name='requisicaoamostra',
            name='tipo_amostra',
            field=models.ForeignKey(blank=True, help_text='Tipo de amostra (ex: Biópsia, Citologia, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras', to='operacao.tipoamostra', verbose_name='Tipo de amostra'),
        ),
    ]
