# Generated by Django 5.2.9 on 2025-12-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0017_popular_tipos_pendencia_etapa3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criar tabela MotivoExclusaoAmostra primeiro (LogAlteracaoAmostra depende dela)
        migrations.CreateModel(
            name='MotivoExclusaoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.PositiveSmallIntegerField(db_index=True, help_text='Código único do motivo de exclusão', unique=True, verbose_name='Código')),
                ('descricao', models.CharField(help_text='Descrição do motivo de exclusão', max_length=200, verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Indica se o motivo está disponível para uso', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motivo de Exclusão de Amostra',
                'verbose_name_plural': 'Motivos de Exclusão de Amostra',
                'db_table': 'motivo_exclusao_amostra',
                'ordering': ('codigo',),
            },
        ),
        # Criar tabela LogAlteracaoAmostra
        migrations.CreateModel(
            name='LogAlteracaoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_barras_requisicao', models.CharField(db_index=True, help_text='Código de barras da requisição (desnormalizado para auditoria)', max_length=64, verbose_name='Código de barras da requisição')),
                ('cod_barras_amostra', models.CharField(db_index=True, help_text='Código de barras da amostra alterada', max_length=64, verbose_name='Código de barras da amostra')),
                ('tipo_alteracao', models.CharField(choices=[('ADICAO', 'Adição'), ('EXCLUSAO', 'Exclusão')], db_index=True, help_text='Tipo da alteração realizada (adição ou exclusão)', max_length=10, verbose_name='Tipo de alteração')),
                ('etapa', models.CharField(db_index=True, help_text='Etapa em que a alteração foi realizada (ex: TRIAGEM3, RECEBIMENTO)', max_length=20, verbose_name='Etapa')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observações adicionais sobre a alteração', verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Log de Alteração de Amostra',
                'verbose_name_plural': 'Logs de Alteração de Amostra',
                'db_table': 'log_alteracao_amostra',
                'ordering': ('-created_at',),
            },
        ),
        # Adicionar FKs ao LogAlteracaoAmostra
        migrations.AddField(
            model_name='logalteracaoamostra',
            name='requisicao',
            field=models.ForeignKey(help_text='Requisição associada à alteração', on_delete=django.db.models.deletion.CASCADE, related_name='logs_alteracao_amostra', to='operacao.dadosrequisicao', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='logalteracaoamostra',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que realizou a alteração', on_delete=django.db.models.deletion.PROTECT, related_name='logs_alteracao_amostra', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='logalteracaoamostra',
            name='motivo_exclusao',
            field=models.ForeignKey(blank=True, help_text='Motivo da exclusão (apenas para exclusões)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_exclusao', to='operacao.motivoexclusaoamostra', verbose_name='Motivo de exclusão'),
        ),
        # Adicionar índices ao LogAlteracaoAmostra
        migrations.AddIndex(
            model_name='logalteracaoamostra',
            index=models.Index(fields=['requisicao', '-created_at'], name='idx_log_req_created'),
        ),
        migrations.AddIndex(
            model_name='logalteracaoamostra',
            index=models.Index(fields=['tipo_alteracao', '-created_at'], name='idx_log_tipo_created'),
        ),
        migrations.AddIndex(
            model_name='logalteracaoamostra',
            index=models.Index(fields=['usuario', '-created_at'], name='idx_log_user_created'),
        ),
    ]
