# Generated by Django 5.2.9 on 2025-12-16 20:18
# Editado manualmente para incluir apenas os campos novos de Korus

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0022_add_ordem_amostra_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrequisicao',
            name='convenio_paciente',
            field=models.CharField(blank=True, help_text='Nome do convênio do paciente (API Korus)', max_length=100, verbose_name='Convênio'),
        ),
        migrations.AddField(
            model_name='dadosrequisicao',
            name='matricula_paciente',
            field=models.CharField(blank=True, help_text='Matrícula do paciente no convênio (API Korus)', max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='dadosrequisicao',
            name='plano_paciente',
            field=models.CharField(blank=True, help_text='Nome do plano do paciente (API Korus)', max_length=100, verbose_name='Plano'),
        ),
    ]
