# Generated by Django 5.2.9 on 2025-12-16 22:13
# Editado manualmente para incluir apenas a alteração do campo data_recebimento_nto

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0023_add_campos_korus_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosrequisicao',
            name='data_recebimento_nto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
