# Generated by Django 5.2.9 on 2025-12-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0026_popular_pendencias_etapa2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, help_text='Código único do protocolo (gerado automaticamente)', max_length=30, unique=True, verbose_name='Código do Protocolo')),
                ('crm', models.CharField(help_text='Número do CRM do médico', max_length=20, verbose_name='CRM')),
                ('uf_crm', models.CharField(help_text='Estado do CRM (ex: SP, RJ)', max_length=2, verbose_name='UF do CRM')),
                ('nome_medico', models.CharField(help_text='Nome completo do médico', max_length=200, verbose_name='Nome do Médico')),
                ('medico_validado', models.BooleanField(default=False, help_text='Indica se o médico foi validado via API', verbose_name='Médico Validado')),
                ('arquivo_url', models.CharField(help_text='URL do arquivo PDF no S3', max_length=500, verbose_name='URL do Arquivo')),
                ('arquivo_nome', models.CharField(help_text='Nome original do arquivo enviado', max_length=255, verbose_name='Nome do Arquivo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, default='', help_text='Observações adicionais sobre o protocolo', verbose_name='Observação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='operacao.origem', verbose_name='Origem')),
                ('portador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='operacao.portadorrepresentante', verbose_name='Portador/Representante')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='operacao.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'db_table': 'operacao_protocolo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='protocolo',
            index=models.Index(fields=['codigo'], name='operacao_pr_codigo_c8738e_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolo',
            index=models.Index(fields=['status', '-created_at'], name='operacao_pr_status_e0cbfd_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolo',
            index=models.Index(fields=['unidade', '-created_at'], name='operacao_pr_unidade_8bc7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolo',
            index=models.Index(fields=['crm', 'uf_crm'], name='operacao_pr_crm_b3e876_idx'),
        ),
    ]
