# Generated by Django 5.2.9 on 2025-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0027_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='nome_medico',
            field=models.CharField(blank=True, default='', help_text='Nome completo do médico (vazio se pendente de validação)', max_length=200, verbose_name='Nome do Médico'),
        ),
    ]
