# Generated by Django 5.2.9 on 2025-12-18 18:11
# Simplificada para incluir apenas criação do sistema de tarefas

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0028_alter_nome_medico_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criar TipoTarefa primeiro (Tarefa depende dele)
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Código único do tipo de tarefa (ex: CADASTRO_MEDICO)', max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(help_text='Nome descritivo do tipo de tarefa', max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição detalhada do tipo de tarefa', verbose_name='Descrição')),
                ('prazo_dias', models.PositiveIntegerField(default=3, help_text='Prazo padrão em dias para conclusão', verbose_name='Prazo (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Tarefa',
                'verbose_name_plural': 'Tipos de Tarefa',
                'ordering': ['nome'],
            },
        ),
        # Criar Tarefa com todos os campos e FKs
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, help_text='Código único gerado automaticamente', max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(help_text='Título resumido da tarefa', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição detalhada da tarefa', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='A_FAZER', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('origem', models.CharField(choices=[('SISTEMA', 'Sistema'), ('GESTOR', 'Gestor')], default='GESTOR', help_text='Quem criou a tarefa: Sistema ou Gestor', max_length=20, verbose_name='Origem')),
                ('data_prazo', models.DateField(blank=True, help_text='Data limite para conclusão', null=True, verbose_name='Data de Prazo')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Quando a tarefa foi iniciada (status EM_ANDAMENTO)', null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Quando a tarefa foi concluída', null=True, verbose_name='Data de Conclusão')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Observações adicionais ou histórico de ações', verbose_name='Observações')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Usuário que criou a tarefa (null se criada pelo sistema)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('protocolo', models.ForeignKey(blank=True, help_text='Protocolo relacionado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='operacao.protocolo', verbose_name='Protocolo')),
                ('requisicao', models.ForeignKey(blank=True, help_text='Requisição relacionada (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='operacao.dadosrequisicao', verbose_name='Requisição')),
                ('responsavel', models.ForeignKey(help_text='Colaborador responsável pela execução', on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('tipo', models.ForeignKey(blank=True, help_text='Tipo pré-definido (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='operacao.tipotarefa', verbose_name='Tipo de Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        # Índices para Tarefa
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['status', '-created_at'], name='operacao_ta_status_380e68_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['responsavel', 'status'], name='operacao_ta_respons_1ad008_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['data_prazo'], name='operacao_ta_data_pr_63a77e_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['origem', '-created_at'], name='operacao_ta_origem_51c82e_idx'),
        ),
    ]
