# Generated by Django 5.2.9 on 2025-12-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbAmostra',
            fields=[
            ],
            options={
                'verbose_name': 'amostra',
                'verbose_name_plural': 'amostra',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.amostra',),
        ),
        migrations.CreateModel(
            name='DbHistorico',
            fields=[
            ],
            options={
                'verbose_name': 'requisicao_status_historico',
                'verbose_name_plural': 'requisicao_status_historico',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.requisicaostatushistorico',),
        ),
        migrations.CreateModel(
            name='DbLogRecebimento',
            fields=[
            ],
            options={
                'verbose_name': 'log_recebimento',
                'verbose_name_plural': 'log_recebimento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.logrecebimento',),
        ),
        migrations.CreateModel(
            name='DbPortador',
            fields=[
            ],
            options={
                'verbose_name': 'portador_representante',
                'verbose_name_plural': 'portador_representante',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.portadorrepresentante',),
        ),
        migrations.CreateModel(
            name='DbRequisicao',
            fields=[
            ],
            options={
                'verbose_name': 'requisicao',
                'verbose_name_plural': 'requisicao',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.dadosrequisicao',),
        ),
        migrations.CreateModel(
            name='DbStatusRequisicao',
            fields=[
            ],
            options={
                'verbose_name': 'status_requisicao',
                'verbose_name_plural': 'status_requisicao',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.statusrequisicao',),
        ),
        migrations.CreateModel(
            name='DbUnidade',
            fields=[
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidade',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.unidade',),
        ),
    ]
