# Generated by Django 5.2.9 on 2025-12-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0006_adicionar_tabelas_arquivos'),
        ('tabelas_sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbRequisicaoArquivo',
            fields=[
            ],
            options={
                'verbose_name': 'requisicao_arquivo',
                'verbose_name_plural': 'requisicao_arquivo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.requisicaoarquivo',),
        ),
        migrations.CreateModel(
            name='DbTipoArquivo',
            fields=[
            ],
            options={
                'verbose_name': 'tipo_arquivo',
                'verbose_name_plural': 'tipo_arquivo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operacao.tipoarquivo',),
        ),
        migrations.AlterModelOptions(
            name='dbrequisicao',
            options={'verbose_name': 'dados_requisicao', 'verbose_name_plural': 'dados_requisicao'},
        ),
    ]
