# Generated by Django 5.2.9 on 2025-12-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Texto exibido no menu', max_length=100, verbose_name='Título')),
                ('icone', models.CharField(blank=True, default='📄', help_text='Emoji ou classe CSS do ícone (ex: 🏠, fa-home)', max_length=50, verbose_name='Ícone')),
                ('url_name', models.CharField(blank=True, default='', help_text='Nome da URL Django (ex: operacao:triagem). Deixe vazio para itens de grupo.', max_length=100, verbose_name='Nome da URL')),
                ('url_externa', models.URLField(blank=True, default='', help_text='URL externa completa. Tem prioridade sobre url_name.', verbose_name='URL Externa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar temporariamente', verbose_name='Ativo')),
                ('abrir_nova_aba', models.BooleanField(default=False, help_text='Marque para abrir link em nova aba', verbose_name='Abrir em nova aba')),
                ('divisor_antes', models.BooleanField(default=False, help_text='Adiciona uma linha divisória antes deste item', verbose_name='Divisor antes')),
                ('roles_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de roles que podem ver este item. Vazio = todos podem ver.', verbose_name='Roles permitidos')),
                ('parent', models.ForeignKey(blank=True, help_text='Deixe vazio para itens de nível superior', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Item pai')),
            ],
            options={
                'verbose_name': 'Item de Menu',
                'verbose_name_plural': 'Itens de Menu',
                'db_table': 'core_menu_item',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
