# Generated by Django 5.2.9 on 2025-12-18 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_menu_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('medico_duplicado', 'Médico Duplicado'), ('medico_nao_encontrado', 'Médico Não Encontrado'), ('notificacao_geral', 'Notificação Geral')], help_text='Tipo de email (define quando este template será usado)', max_length=50, unique=True, verbose_name='Tipo')),
                ('nome', models.CharField(help_text='Nome descritivo para identificação', max_length=100, verbose_name='Nome')),
                ('email_destino', models.TextField(help_text='Email(s) de destino separados por vírgula. Ex: email1@femme.com.br, email2@femme.com.br', verbose_name='Email(s) Destino')),
                ('assunto_padrao', models.CharField(help_text='Assunto padrão do email. Pode usar placeholders: {crm}, {uf}, {data}', max_length=200, verbose_name='Assunto Padrão')),
                ('corpo_padrao', models.TextField(help_text='Corpo padrão do email (HTML permitido). Placeholders: {crm}, {uf}, {medicos}, {usuario}, {data}', verbose_name='Corpo Padrão')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar este template', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
                'db_table': 'core_configuracao_email',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(help_text='Área/módulo relacionado. Ex: Cadastro Protocolo, Triagem', max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(help_text='Descrição do motivo do email. Ex: medico_duplicado, medico_nao_encontrado', max_length=200, verbose_name='Descrição')),
                ('destinatario', models.TextField(help_text='Email(s) de destino', verbose_name='Destinatário(s)')),
                ('assunto', models.CharField(max_length=300, verbose_name='Assunto')),
                ('corpo', models.TextField(help_text='Conteúdo completo do email enviado', verbose_name='Corpo')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status')),
                ('erro_mensagem', models.TextField(blank=True, default='', help_text='Detalhes do erro caso o envio tenha falhado', verbose_name='Mensagem de Erro')),
                ('enviado_em', models.DateTimeField(blank=True, help_text='Data/hora do envio efetivo', null=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Log de Envio de Email',
                'verbose_name_plural': 'Logs de Envio de Email',
                'db_table': 'core_log_envio_email',
                'ordering': ['-created_at'],
            },
        ),
    ]
