# Generated by Django 5.2.9 on 2025-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adicionar_modelos_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemail',
            name='email_resposta',
            field=models.EmailField(blank=True, default='', help_text='Email que receberá as respostas. Ex: gestora@femme.com.br. Se vazio, usa o email de envio padrão.', max_length=254, verbose_name='Email para Resposta (Reply-To)'),
        ),
    ]
