# Generated by Django 5.2.9 on 2025-12-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_menu_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoemail',
            name='tipo',
            field=models.CharField(choices=[('medico_duplicado', 'Médico Duplicado'), ('medico_nao_encontrado', 'Médico Não Encontrado'), ('medico_sem_destino', 'Médico Sem Destino'), ('notificacao_geral', 'Notificação Geral')], help_text='Tipo de email (define quando este template será usado)', max_length=50, unique=True, verbose_name='Tipo'),
        ),
    ]
